# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Jourden\Desktop\Alloy\mygui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1046, 563)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(210, 110, 51, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(310, 110, 111, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.OUTPUT = QtWidgets.QLabel(self.centralwidget)
        self.OUTPUT.setGeometry(QtCore.QRect(580, 90, 431, 301))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.OUTPUT.setFont(font)
        self.OUTPUT.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.OUTPUT.setStyleSheet("background-color : rgb(255, 255, 255)")
        self.OUTPUT.setText("")
        self.OUTPUT.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OUTPUT.setObjectName("OUTPUT")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(560, 10, 461, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.Edge = QtWidgets.QLineEdit(self.centralwidget)
        self.Edge.setGeometry(QtCore.QRect(270, 70, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Edge.setFont(font)
        self.Edge.setAlignment(QtCore.Qt.AlignCenter)
        self.Edge.setObjectName("Edge")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(40, 70, 231, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(540, 40, 541, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(530, 0, 20, 521))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.Error_message = QtWidgets.QLabel(self.centralwidget)
        self.Error_message.setGeometry(QtCore.QRect(570, 410, 451, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Error_message.setFont(font)
        self.Error_message.setText("")
        self.Error_message.setAlignment(QtCore.Qt.AlignCenter)
        self.Error_message.setObjectName("Error_message")
        self.Error_message_2 = QtWidgets.QLabel(self.centralwidget)
        self.Error_message_2.setGeometry(QtCore.QRect(570, 460, 451, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Error_message_2.setFont(font)
        self.Error_message_2.setText("")
        self.Error_message_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Error_message_2.setObjectName("Error_message_2")
        self.Propo_2 = QtWidgets.QLabel(self.centralwidget)
        self.Propo_2.setGeometry(QtCore.QRect(40, 410, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Propo_2.setFont(font)
        self.Propo_2.setObjectName("Propo_2")
        self.seeding = QtWidgets.QLineEdit(self.centralwidget)
        self.seeding.setGeometry(QtCore.QRect(210, 410, 91, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.seeding.setFont(font)
        self.seeding.setObjectName("seeding")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(310, 150, 101, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LEP4 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.LEP4.setFont(font)
        self.LEP4.setAlignment(QtCore.Qt.AlignCenter)
        self.LEP4.setObjectName("LEP4")
        self.verticalLayout.addWidget(self.LEP4)
        self.LEP5 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.LEP5.setFont(font)
        self.LEP5.setAlignment(QtCore.Qt.AlignCenter)
        self.LEP5.setObjectName("LEP5")
        self.verticalLayout.addWidget(self.LEP5)
        self.LEP3 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.LEP3.setFont(font)
        self.LEP3.setAlignment(QtCore.Qt.AlignCenter)
        self.LEP3.setObjectName("LEP3")
        self.verticalLayout.addWidget(self.LEP3)
        self.LEP2 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.LEP2.setFont(font)
        self.LEP2.setAlignment(QtCore.Qt.AlignCenter)
        self.LEP2.setObjectName("LEP2")
        self.verticalLayout.addWidget(self.LEP2)
        self.LEP1 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.LEP1.setFont(font)
        self.LEP1.setAlignment(QtCore.Qt.AlignCenter)
        self.LEP1.setObjectName("LEP1")
        self.verticalLayout.addWidget(self.LEP1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(190, 150, 94, 201))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LEI1 = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.LEI1.setFont(font)
        self.LEI1.setAlignment(QtCore.Qt.AlignCenter)
        self.LEI1.setObjectName("LEI1")
        self.verticalLayout_2.addWidget(self.LEI1)
        self.LEI2 = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.LEI2.setFont(font)
        self.LEI2.setAlignment(QtCore.Qt.AlignCenter)
        self.LEI2.setObjectName("LEI2")
        self.verticalLayout_2.addWidget(self.LEI2)
        self.LEI3 = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.LEI3.setFont(font)
        self.LEI3.setAlignment(QtCore.Qt.AlignCenter)
        self.LEI3.setObjectName("LEI3")
        self.verticalLayout_2.addWidget(self.LEI3)
        self.LEI4 = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.LEI4.setFont(font)
        self.LEI4.setAlignment(QtCore.Qt.AlignCenter)
        self.LEI4.setObjectName("LEI4")
        self.verticalLayout_2.addWidget(self.LEI4)
        self.LEI5 = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.LEI5.setFont(font)
        self.LEI5.setAlignment(QtCore.Qt.AlignCenter)
        self.LEI5.setObjectName("LEI5")
        self.verticalLayout_2.addWidget(self.LEI5)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(90, 150, 150, 199))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.proportionedit = QtWidgets.QLineEdit(self.centralwidget)
        self.proportionedit.setGeometry(QtCore.QRect(360, 370, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.proportionedit.setFont(font)
        self.proportionedit.setAlignment(QtCore.Qt.AlignCenter)
        self.proportionedit.setObjectName("proportionedit")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(440, 370, 20, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(41, 370, 312, 28))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.RanVacancy = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.RanVacancy.setFont(font)
        self.RanVacancy.setObjectName("RanVacancy")
        self.horizontalLayout.addWidget(self.RanVacancy)
        self.random_but = QtWidgets.QCheckBox(self.layoutWidget3)
        self.random_but.setText("")
        self.random_but.setObjectName("random_but")
        self.horizontalLayout.addWidget(self.random_but)
        self.Propo = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Propo.setFont(font)
        self.Propo.setObjectName("Propo")
        self.horizontalLayout.addWidget(self.Propo)
        self.estimate_text = QtWidgets.QLabel(self.centralwidget)
        self.estimate_text.setGeometry(QtCore.QRect(440, 70, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.estimate_text.setFont(font)
        self.estimate_text.setText("")
        self.estimate_text.setObjectName("estimate_text")
        self.Button_estimate = QtWidgets.QPushButton(self.centralwidget)
        self.Button_estimate.setGeometry(QtCore.QRect(320, 70, 111, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Button_estimate.setFont(font)
        self.Button_estimate.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(138, 138, 138, 255), stop:1 rgba(255, 255, 255, 255))")
        self.Button_estimate.setObjectName("Button_estimate")
        self.Propo_3 = QtWidgets.QLabel(self.centralwidget)
        self.Propo_3.setGeometry(QtCore.QRect(310, 410, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Propo_3.setFont(font)
        self.Propo_3.setObjectName("Propo_3")
        self.textn = QtWidgets.QLineEdit(self.centralwidget)
        self.textn.setGeometry(QtCore.QRect(410, 410, 111, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.textn.setFont(font)
        self.textn.setObjectName("textn")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(42, 21, 386, 34))
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.radioButton_fcc = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.radioButton_fcc.setFont(font)
        self.radioButton_fcc.setObjectName("radioButton_fcc")
        self.horizontalLayout_4.addWidget(self.radioButton_fcc)
        self.radioButton_bcc = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.radioButton_bcc.setFont(font)
        self.radioButton_bcc.setObjectName("radioButton_bcc")
        self.horizontalLayout_4.addWidget(self.radioButton_bcc)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.CalE_but = QtWidgets.QCheckBox(self.widget)
        self.CalE_but.setText("")
        self.CalE_but.setObjectName("CalE_but")
        self.horizontalLayout_2.addWidget(self.CalE_but)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(110, 450, 138, 79))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Button_example = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Button_example.setFont(font)
        self.Button_example.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(138, 138, 138, 255), stop:1 rgba(255, 255, 255, 255))")
        self.Button_example.setObjectName("Button_example")
        self.verticalLayout_4.addWidget(self.Button_example)
        self.Button3 = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Button3.setFont(font)
        self.Button3.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(124, 124, 124, 255), stop:1 rgba(255, 255, 255, 255))")
        self.Button3.setObjectName("Button3")
        self.verticalLayout_4.addWidget(self.Button3)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(260, 450, 141, 79))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Button1 = QtWidgets.QPushButton(self.widget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Button1.setFont(font)
        self.Button1.setStyleSheet("background-color:\n"
"qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(124, 124, 124, 255), stop:1 rgba(255, 255, 255, 255))")
        self.Button1.setObjectName("Button1")
        self.verticalLayout_5.addWidget(self.Button1)
        self.Button2 = QtWidgets.QPushButton(self.widget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Button2.setFont(font)
        self.Button2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(124, 124, 124, 255), stop:1 rgba(255, 255, 255, 255));")
        self.Button2.setObjectName("Button2")
        self.verticalLayout_5.addWidget(self.Button2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1046, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "Item"))
        self.label_9.setText(_translate("MainWindow", "Proportion"))
        self.label_10.setText(_translate("MainWindow", "OUTPUT"))
        self.label_12.setText(_translate("MainWindow", "Atom number on edge"))
        self.Propo_2.setText(_translate("MainWindow", "Seeding number"))
        self.label_2.setText(_translate("MainWindow", "  Atom1 "))
        self.label_3.setText(_translate("MainWindow", "  Atom2  "))
        self.label_4.setText(_translate("MainWindow", "  Atom3  "))
        self.label_5.setText(_translate("MainWindow", "  Atom4  "))
        self.label_6.setText(_translate("MainWindow", "  Atom5  "))
        self.label_16.setText(_translate("MainWindow", "%"))
        self.RanVacancy.setText(_translate("MainWindow", "Random vacancy"))
        self.Propo.setText(_translate("MainWindow", "Proportion"))
        self.Button_estimate.setText(_translate("MainWindow", "Estimate # "))
        self.Propo_3.setText(_translate("MainWindow", "Textname"))
        self.label.setText(_translate("MainWindow", "Structure"))
        self.radioButton_fcc.setText(_translate("MainWindow", "fcc"))
        self.radioButton_bcc.setText(_translate("MainWindow", "bcc"))
        self.label_7.setText(_translate("MainWindow", "Cal. Entropy"))
        self.Button_example.setText(_translate("MainWindow", "Example"))
        self.Button3.setText(_translate("MainWindow", "Show Output"))
        self.Button1.setText(_translate("MainWindow", "Calculate"))
        self.Button2.setText(_translate("MainWindow", "Show Text"))

